### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by gunnicus** [JhottMaster/PixyUSBdotNET#1]
Hi, I'm using windows 10 and visual studio 2015. I downloaded your project and trying to build but I'm getting the following errors. Seems like something is missing. Do you have any idea how to fix this? Sorry I don't know anything about c++.
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/chrono.hpp': No such file or directory	pixyusblib	c:\users\todd\documents\robotic\pixyusbdotnet-master\pixyusblib\src\utils\timer.hpp	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/chrono.hpp': No such file or directory	pixyusblib	c:\users\todd\documents\robotic\pixyusbdotnet-master\pixyusblib\src\utils\timer.hpp	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/thread.hpp': No such file or directory	pixyusblib	c:\users\todd\documents\robotic\pixyusbdotnet-master\pixyusblib\src\pixyinterpreter.hpp	20	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/thread.hpp': No such file or directory	pixyusblib	c:\users\todd\documents\robotic\pixyusbdotnet-master\pixyusblib\src\pixyinterpreter.hpp	20	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/chrono.hpp': No such file or directory	pixyusblib	c:\users\todd\documents\robotic\pixyusbdotnet-master\pixyusblib\src\utils\timer.hpp	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: 'build\cmakefiles\feature_tests.cxx': No such file or directory	pixyusblib	C:\Users\TODD\Documents\Robotic\PixyUSBdotNET-master\pixyusblib\c1xx	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: 'build\cmakefiles\3.2.3\compileridcxx\CMakeCXXCompilerId.cpp': No such file or directory	pixyusblib	C:\Users\TODD\Documents\Robotic\PixyUSBdotNET-master\pixyusblib\c1xx	1

**Comment by gunnicus** [comment]
Ok, I dowanloaded the boost_1_63_0, and in pixyusblib project Configuration Properties > C/C++ > General > Additional Include Directories, I entered the path to the Boost root directory C:\Users\TODD\Documents\Robotic\boost_1_63_0\boost. Now I'm only getting these 2 errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	**Cannot open source file: 'build\cmakefiles\feature_tests.cxx': No such file or directory**	pixyusblib	C:\Users\TODD\Documents\Robotic\PixyUSBdotNET-master\pixyusblib\c1xx	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	**Cannot open source file: 'build\cmakefiles\3.2.3\compileridcxx\CMakeCXXCompilerId.cpp': No such file or directory**	pixyusblib	C:\Users\TODD\Documents\Robotic\PixyUSBdotNET-master\pixyusblib\c1xx	1	

Please help.

**Comment by gunnicus** [comment]
Ok, after a few more steps. Finally it is building now.
1. I removed CMakeCXXCompilerId.cpp and feature_tests.cxx from pixyusblib project(in Source Files folder )
2. I changed pixyusblib project Configuration Properties > Linker > General > Additional Library Directories to C:\Users\TODD\Documents\Robotic\boost_1_63_0\stage\lib

It is building now.

**Comment by JhottMaster** [comment]
Hey @gunnicus , I'm glad you were able to resolve issue- thank you especially for leaving your comments on the fix. I haven't looked at this project in a while and I'm glad someone else can make use of it.

**Comment by gunnicus** [comment]
Hi @JhottMaster thanks for making this wrapper. I haven't got the camera yet, will do more testing once I got the camera, just trying to get this project to build. I'm wondering how the pixy camera going? Doesn't look like they got much update lately, is that pixy camera dead?

**Comment by JhottMaster** [comment]
I've wondered the same. I don't know if it's _**dead**_, but it does seem it hasn't seen as much work. At one point there was the idea of facial recognition being possible but it seems it never materialized. I got busy with school and haven't touched my PIXY cam project either, but I recently funded a kick starter for a similar project that seems to have much more flexibility and much more power. I just it yesterday: https://www.kickstarter.com/projects/1602548140/jevois-open-source-quad-core-smart-machine-vision
I haven't played with it yet.

**Comment by gunnicus** [comment]
Thanks @JhottMaster ,that looks very interesting. I'm wondering if they have the 'signature' feature like pixy camera which I can select the color I want to track. And if they have .net library I can use straight away. 
I was trying to make a following bot, initially I was using Kinect V2 but there is a big problem with Kinect which is while kinect sensor is moving, it lost track of things.
So I'm thinking moving onto different camera sensors, pixy camera looks like a possible candidate espically you made a .net wrapper for it :)
